#Recuperación de datos
GET http://localhost:1234/movies/

# REcuperar datos por ID
GET http://localhost:1234/movies/1

# REcuperar todos los datos de algo en especifíco
GET http://localhost:1234/movies?genre=Terror
